### PR TITLE
feat: switch back to nautobot helm chart

### PR DESCRIPTION
**Pull request by cardoe**
Switch back to using the nautobot helm chart now that the fixes are merged upstream. This will allow us to remain current with nautobot releases going forward.

### CODE REVIEW

**Comment by cardoe** [comment]
So leaving this as draft because the NAUTOBOT_SECRET_KEY doesn't seem to be respected and I believe ArgoCD will always load the tests.

**Comment by cardoe** [comment]
I think it's not working because of https://github.com/argoproj/argo-cd/issues/13220

**Comment by cardoe** [comment]
Alright came up with a work around by using the URL to this repo. I'll try and see if I can't submit a fix upstream for ArgoCD.

**Comment by cardoe** [comment]
This change will drag us forward to Nautobot 2.1.9 as well since that's what the helm charts package.

**Review by nicholaskuechler — APPROVED** [review]

**Pull request merged**
