### PR TITLE
fix(typo): fix typo

### PR DESCRIPTION
**Pull request by nicholaskuechler**

### CODE REVIEW

**Comment by nicholaskuechler** [comment]
> How come spellcheck didn't catch that?

That's a good question and what I'm looking at next.

**Comment by nicholaskuechler** [comment]
I've requested the typo and fix be added to upstream typos repo: https://github.com/crate-ci/typos/issues/1106#issuecomment-2400369752

**Comment by szepeviktor** [comment]
There's more.
https://github.com/rackerlabs/understack/blob/46bedd91986320d4677a00f39944d2760e3decb2/docs/kubernetes.md?plain=1#L49

https://github.com/hunspell/hunspell

**Comment by szepeviktor** [comment]
@nicholaskuechler That is all. I've finished checking this repository.

**Comment by nicholaskuechler** [comment]
Thanks, @szepeviktor, we appreciate it!

**Comment by szepeviktor** [comment]
Somehow the correction of "Pasasword" was reverted.

**Review by cardoe — APPROVED** [review]

**Pull request merged**
